name: AIPRChecker - Check for security issues and code smells
on: [pull_request, pull_request_target]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run AIPRChecker
        uses: AI-Gents/AIPRChecker@main
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'gpt-4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
